### ISSUE TITLE
Frontpage filtrering

### ISSUE THREAD

**Issue by mrasmg** [mrasmg/Portalen#11]
Er det muligt enten:

1. at indsætte et felt som hedder "Genre" (som vil kunne figurere som "overskrift" på den fine dropdown menu, så dropdown ikke starter med "Alt"). Og det samme for alle månederne, så den ikke starter med Februar - lave en filtering som er navngivet "Måneder" som "overskrift" i dropdownmenuen.

ELLER

2. lave en lille overskrift oven over dropdown boksene, hvor der står: "Genre", Måned", "År".

**Comment by Kocxxx** [comment]
Alt er ændret til Genre.
Årstal er ændret til dropdown

Månederne kan vi desværre kun gøre sådan, at den aktive måned er i feltet.
