### ISSUE TITLE
Design på subsite (EnventOn single page)

### ISSUE THREAD

**Issue by mrasmg** [mrasmg/Portalen#12]
Som jeg ser det, er der lige nu 3 forskellige designs på undersiderne.

Den som er sat op til eventet: En fremmede flytter ind (januar md.) er virkelig god og en rigtig fin løsning ud fra vores sidste ønsker.

Spørgsmål: Hvad er årsagen til at de andre events er anderledes opsat? Kan vi overskrive koder, så design bliver alignet på alle undersider (også nye kommende events som Portalen selv indtaster)?

![xx.jpg](https://images.zenhubusercontent.com/5a30fe1e8a75884b908af78b/41bfae2d-c54c-4e69-a5f6-b6cad39f14ba)

![xxx.jpg](https://images.zenhubusercontent.com/5a30fe1e8a75884b908af78b/f667ddbc-d27c-41b7-bbd8-003ad1fa3707)

![xxxx.jpg](https://images.zenhubusercontent.com/5a30fe1e8a75884b908af78b/6d293a23-5989-4fc6-a148-d25708104ec3)

**Comment by Kocxxx** [comment]
jeg kigger på det

**Comment by Kocxxx** [comment]
Jeg kan se, at hvis et eksisterende event bliver duplicated virker det.
