### ISSUE TITLE
Filtrereing - årstal

### ISSUE THREAD

**Issue by mrasmg** [mrasmg/Portalen#14]
2018 er aktivt valgt fra starten.
Baggrunden på knappen bør være samme grå farve som på "Genre" og "Måneder".

Når en knap (m årstal) er inaktiv, bør den ligne "2019" uden baggrundsfarve
Når en knap er aktiv bør den ligne "2018" med en mørkegrå baggrund (som Genre og Måneder).

![aaaa.jpg](https://images.zenhubusercontent.com/5a30fe1e8a75884b908af78b/6b60c137-51d7-4dc0-8898-b182dd8e9b31)

![aaaaa.jpg](https://images.zenhubusercontent.com/5a30fe1e8a75884b908af78b/ce1115f2-30cf-4c81-b5fe-b75b4733407a)

**Comment by Kocxxx** [comment]
jeg skal se hvad jeg kan gøre, pt bliver det hele overskrevet grundet plguin
