### ISSUE TITLE
Knapper

### ISSUE THREAD

**Issue by mrasmg** [mrasmg/Portalen#16]
Det lader til at knapperne har fået en ny margin / indstilling.
De er alle rykket til venstre (og står umiddelbart i "minus" i forhold til tekst i samme blokke).

De skulle gerne på plads igen.

**Comment by Kocxxx** [comment]
billede?

**Comment by mrasmg** [comment]
Her er et par eks. på at knappen har rykket sig

![1](https://user-images.githubusercontent.com/34507038/36673157-1dceec2a-1b02-11e8-964b-2921ebcb06f2.jpg)
![v](https://user-images.githubusercontent.com/34507038/36673158-1dea26b6-1b02-11e8-8516-cf457f6795be.jpg)
![x](https://user-images.githubusercontent.com/34507038/36673159-1e02f0ba-1b02-11e8-9048-4eb8a28c8df7.jpg)

**Comment by Kocxxx** [comment]
Fikset :)
