### ISSUE TITLE
FIltrering skal ændres

### ISSUE THREAD

**Issue by mrasmg** [mrasmg/Portalen#3]
søgefelt skal blive
Vis anden måned (knap)- fjernes

Dropdown menu
Genre (mulighed for at oprette de forskellige og matche den enkle til den pågældende genre)
Måned / År (gå fra indeværende måned frem til... uendeligt med events)
Søgefelt (Meta dataen)

Ref. Amager bio

 ![Skærmbillede 2018-02-21 14.29.43.png](https://images.zenhubusercontent.com/5a30fe1e8a75884b908af78b/5aebf16b-7817-4e55-835c-002d57342647)

**Comment by mrasmg** [comment]
<img width="960" alt="skaermbillede 2018-02-21 14 29 59" src="https://user-images.githubusercontent.com/34507038/36482506-d188f212-1713-11e8-90c0-571281b68d3d.png">

**Comment by Kocxxx** [comment]
Plugin'et understøtter ikke dropdowns på den måde. Så skal vi til at overveje, at slette dette plugin og kode det hele forfra og i bunden. Således at det er transparent og virker nøjagtigt efter hensigten

**Comment by mrasmg** [comment]
Vi ved at dette plugin ikke understøtter samme filtrerings udtryk som Amager Bio.
Så jeg har forsøgt i designfilen at tage højde for at genbruge nogle af elementerne som jeg formoder er integreret i EventOn kalenderen.

Se vedhæftet designfil. Og meld endelig tilbage...
![portalen_front_01](https://user-images.githubusercontent.com/34507038/36533025-a8e392a4-17c2-11e8-8fd8-5186712b1f57.jpg)

**Comment by Kocxxx** [comment]
Prøv gerne at tjek nu (ikke tilpasset mobil endnu). Ville det være funktionelt ? :)

De sidste hover-farver skal vi nok få styr på.

**Comment by mrasmg** [comment]
Fantastisk - jeg vender den lige med michael når han ankommer.

SP: Er det umuligt at integrere måneder og år i et filtreringsfelt? Hvis ja, så kunne det være man kunne lægge årene ind i ét enkelt filter (så både 2018 og 2019 stod i et felt - som genre og måneder?)
