### ISSUE TITLE
Forside / Overskrift

### ISSUE THREAD

**Issue by mrasmg** [mrasmg/Portalen#4]
Filtrering af events

3 menuer:
genre
måned 
søgefelt

Fjern Februar 2018
ændre Filter events / dropdown menu
ændre Genre / koncert /dropdown menu

![Skærmbillede 2018-02-21 14.35.20.png](https://images.zenhubusercontent.com/5a30fe1e8a75884b908af78b/fc27560c-fdc2-4794-a493-dfbcdd59c535)

**Comment by Kocxxx** [comment]
3 menuer:
genre
måned
søgefelt

og samtidig skal vi fjerne Genre/koncert? Det er vel meningen, at når der kommer flere genrer, så kan folk sortere/til og fra her ?

**Comment by mrasmg** [comment]
Jeg uploader et layout, når Michael har godkendt - ud fra rettelser som blev angivet igår
