### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by mrasmg** [mrasmg/Portalen#5]
Event

Feb (måned) skal være større
Mere space / margin ved datoen

Overskrift (ved smal visning):
Brake line
Fjerne tekst under overskrift (en dansk film af nichole - fjernes)

Font type ned i str

**Comment by Kocxxx** [comment]
Jeg formoder det er på event-siden (det pågældende event).

1. Overskrift ved smal visning (er det i responsive) og i så fald, hvad knæk? pixels. f.eks 967px.
2. Brake line, hvor?
3. Fjerne tekst under overskrift (en dansk film af nichole - fjernes) Formoder, det gælder indenfor en bestemt bredde. Så jeg tager udgangspunkt i det knæk, der fastsættes til overskriften.
4. Font type ned i str, samme som 1 og 3

**Comment by mrasmg** [comment]
Jeg uploader et layout, når Michael har godkendt - ud fra rettelser som blev angivet igår

**Comment by mrasmg** [comment]
![portalen_sub_b](https://user-images.githubusercontent.com/34507038/36533062-c313f290-17c2-11e8-8bf3-5133e8cda003.jpg)

**Comment by Kocxxx** [comment]
Vi kan slet ikke lave det sådan, med det plugin.

Det tætteste vi kommer, er det der er nu.

**Comment by Kocxxx** [comment]
Jeg har tweaket noget css en smule voldsomt nu... kan vi gøre som det er nu, så fint. Så tilpasser jeg mobilgrid. :-)

**Comment by mrasmg** [comment]
Knapperne som du havde på igår, er det muligt at få dem med igen?
Jeg kan se at der er et felt til "Køb billet" og "Hør musik". Men jeg synes ikke rigtig jeg ser "Køb madbillet" eller "Video" feltet længere.

Screenshot er to forskellige events og opsætningen lader ikke til at være aligned... mon der er en årsag til dette?

![a](https://user-images.githubusercontent.com/34507038/36582938-c1cf092c-1873-11e8-9d4b-d2d3c8a94e7a.jpg)
![b](https://user-images.githubusercontent.com/34507038/36582939-c1eb0faa-1873-11e8-93af-261b892a6896.jpg)

**Comment by Kocxxx** [comment]
Der skal tages udgangspunkt i det ene event vi har lavet korrekt opsætning på. Dette kan evt duplikeres. :)
