### ISSUE TITLE
Grå boks ved event

### ISSUE THREAD

**Issue by mrasmg** [mrasmg/Portalen#6]
Kåre kan ikke li' den grå farve bag teksten

Farve ændres  (som design fil / fra i fredags)

**Comment by Kocxxx** [comment]
Hvor ser vi dette henne ? Altså den grå farve. Alt er blåt?...

**Comment by mrasmg** [comment]
Det drejer sig om de grå bokse med tekst tilhørende de enkle events på Frontpage / Events siden
(med dato, titel, kunstner, tid...)

Jeg uploader design fil senere (når Michael har kigget på dem) på et af de andre issues.

![grey_box](https://user-images.githubusercontent.com/34507038/36530568-b6bfeee2-17bb-11e8-9568-765658ed2e1c.jpg)
