### ISSUE TITLE
koncert side (Event)

### ISSUE THREAD

**Issue by mrasmg** [mrasmg/Portalen#7]
Loade så mange event som overhoved muligt
(skal kunne filtreres)

**Comment by Kocxxx** [comment]
Jeg har sat den til, at loade 12 ad gangen. Effekten kan nok først rigtigt ses,når flere af begivenhederne er "lagt på" :-)

**Comment by mrasmg** [comment]
Det lyder fint. 
Men så har jeg et tillægssp.:
Var det ikke meningen at siden ikke skulle være opdelt i måneder (før man filtrere) og at siden skulle liste ... både 50 og 100 events (uendeligt når man bevæger sig nedad på sitet)?
