### ISSUE TITLE
Single event page

### ISSUE THREAD

**Issue by mrasmg** [mrasmg/Portalen#8]
Fjern "En dansk film af nicole n. Horany

Fjern "Genre: Seniorbio / Pris 100"

****

Event info

Fjern 4 bokse:
Tid
Sted
Læs mere link
Kalender

***
Event info skal kun fylde 50% 
Ved siden af 2 ny boks (25% bredde) med: Pris / Køb madbillet

****
![Skærmbillede 2018-02-21 14.50.17.png](https://images.zenhubusercontent.com/5a30fe1e8a75884b908af78b/714db42b-7d13-4bc2-aac9-e0be7dedbc37)![Skærmbillede 2018-02-21 14.50.36.png](https://images.zenhubusercontent.com/5a30fe1e8a75884b908af78b/9d04ffd1-0db7-40cd-a57e-400d9b1b8993)

**Comment by Kocxxx** [comment]
1. Fjern "En dansk film af nicole n. Horany
Hvor skal titlen så fremgå?

**Comment by mrasmg** [comment]
Titlen er: En fremmede flytter ind (øverste linie)

**Comment by Kocxxx** [comment]
fixed
